apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoair
  labels:
    app: contosoair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosoair
  template:
    metadata:
      labels:
        app: contosoair
    spec:
      containers:
        - name: contosoair
          image: contosoairkubecon.azurecr.io/contosoair:latest
          ports:
            - containerPort: 8080