name: Trigger auto deployment for contosoair

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/contosoair-AutoDeployTrigger-cdccbbaf-89a9-4ff7-8cc5-a3f4ce5d5139.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caebea9ed61facr.azurecr.io
          username: ${{ secrets.CONTOSOAIR_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTOSOAIR_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caebea9ed61facr.azurecr.io/contosoair:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTOSOAIR_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n contosoair -g totipu_rg_8558 --server caebea9ed61facr.azurecr.io --username  ${{ secrets.CONTOSOAIR_REGISTRY_USERNAME }} --password ${{ secrets.CONTOSOAIR_REGISTRY_PASSWORD }}
            az containerapp update -n contosoair -g totipu_rg_8558 --image caebea9ed61facr.azurecr.io/contosoair:${{ github.sha }}
